# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a7f64cbe75d517e7727a0ef52488d35168af067c0de6601f3883e247fbea7fa049ded5a635d64bd8f9c9a0739b72634ab7b0d6db05412f25e9070f1730c639

test:
  secret_key_base: 7d6b85cdb99b3e174914798cfc7012434c12c7b43d278cc74519d8f563e8e7a2cfbba68498932db6c3ca940c7edc3c153b01835f20e002b8b29f39653ec91c45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
